#include "NexusOpaqueRevision.h"

#include "Internationalization/Regex.h"

namespace UeNodeNexusBridge::Collaboration
{
static FString NumericPinDefaults(FString Line)
{
    if (!Line.StartsWith(TEXT("CustomProperties Pin ")))
    {
        return Line;
    }
    const bool bNumeric = Line.Contains(TEXT("PinType.PinCategory=\"real\""))
        || Line.Contains(TEXT("PinType.PinCategory=\"float\""))
        || Line.Contains(TEXT("PinType.PinCategory=\"int\""));
    if (!bNumeric)
    {
        return Line;
    }
    for (const TCHAR* Field : { TEXT("DefaultValue"), TEXT("AutogeneratedDefaultValue") })
    {
        const FString Prefix = FString(Field) + TEXT("=\"");
        const int32 Start = Line.Find(Prefix);
        if (Start == INDEX_NONE)
        {
            continue;
        }
        const int32 ValueStart = Start + Prefix.Len();
        const int32 End = Line.Find(TEXT("\""), ESearchCase::CaseSensitive, ESearchDir::FromStart, ValueStart);
        const FString Value = Line.Mid(ValueStart, End - ValueStart);
        if (End != INDEX_NONE && Value.IsNumeric())
        {
            const FString Canonical = FString::Printf(TEXT("%.17g"), FCString::Atod(*Value));
            Line = Line.Left(ValueStart) + Canonical + Line.Mid(End);
        }
    }
    return Line;
}

static FString DecimalText(const FString& Text)
{
    static const FRegexPattern Pattern(TEXT("(?<![A-Za-z0-9_])[+-]?[0-9]+\\.[0-9]+(?![A-Za-z0-9_])"));
    FRegexMatcher Match(Pattern, Text);
    FString Result;
    int32 Last = 0;
    while (Match.FindNext())
    {
        Result += Text.Mid(Last, Match.GetMatchBeginning() - Last);
        FString Number = Match.GetCaptureGroup(0);
        while (Number.EndsWith(TEXT("0")))
        {
            Number.LeftChopInline(1);
        }
        Number.RemoveFromEnd(TEXT("."));
        Result += Number;
        Last = Match.GetMatchEnding();
    }
    return Result + Text.Mid(Last);
}

static FString NormalizeLine(const FString& Source)
{
    const FString Line = NumericPinDefaults(Source.TrimStartAndEnd());
    for (const TCHAR* Field : { TEXT("ErrorMsg="), TEXT("ErrorType="), TEXT("bHasCompilerMessage=") })
    {
        if (Line.StartsWith(Field))
        {
            return FString();
        }
    }
    FString Result;
    int32 Start = 0;
    bool bQuoted = false;
    for (int32 Index = 0; Index < Line.Len(); ++Index)
    {
        if (bQuoted && Line[Index] == TEXT('\\'))
        {
            ++Index;
            continue;
        }
        if (Line[Index] == TEXT('"'))
        {
            const FString Span = Line.Mid(Start, Index - Start + (bQuoted ? 1 : 0));
            Result += bQuoted ? Span : DecimalText(Span);
            Start = Index + (bQuoted ? 1 : 0);
            bQuoted = !bQuoted;
        }
    }
    Result += bQuoted ? Line.Mid(Start) : DecimalText(Line.Mid(Start));
    return Result;
}

static FString ObjectBlock(const TArray<FString>& Lines, int32& Index)
{
    const FString Header = Lines[Index++].TrimStartAndEnd();
    TArray<FString> Entries;
    while (Index < Lines.Num())
    {
        const FString Line = Lines[Index].TrimStartAndEnd();
        if (Line == TEXT("End Object"))
        {
            ++Index;
            break;
        }
        if (Line.StartsWith(TEXT("Begin Object ")))
        {
            Entries.Add(ObjectBlock(Lines, Index));
            continue;
        }
        const FString Normalized = NormalizeLine(Line);
        if (!Normalized.IsEmpty())
        {
            Entries.Add(Normalized);
        }
        ++Index;
    }
    Entries.Sort();
    return Header + TEXT("\n") + FString::Join(Entries, TEXT("\n")) + TEXT("\nEnd Object");
}

FString OpaqueRevisionText(const FString& Text)
{
    TArray<FString> Lines;
    Text.ParseIntoArrayLines(Lines, true);
    TArray<FString> Objects;
    int32 Index = 0;
    while (Index < Lines.Num())
    {
        if (Lines[Index].TrimStartAndEnd().StartsWith(TEXT("Begin Object ")))
        {
            Objects.Add(ObjectBlock(Lines, Index));
        }
        else
        {
            Objects.Add(NormalizeLine(Lines[Index++]));
        }
    }
    Objects.Sort();
    return FString::Join(Objects, TEXT("\n"));
}
}
