#include "NexusBlueprintRevision.h"
#include "NexusOpaqueRevision.h"

#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

namespace UeNodeNexusBridge::Collaboration
{
static TSharedPtr<FJsonValue> CloneValue(const TSharedPtr<FJsonValue>& Value)
{
    if (Value->Type == EJson::Object)
    {
        auto Object = MakeShared<FJsonObject>();
        for (const auto& Pair : Value->AsObject()->Values)
        {
            Object->SetField(Pair.Key, CloneValue(Pair.Value));
        }
        return MakeShared<FJsonValueObject>(Object);
    }
    if (Value->Type == EJson::Array)
    {
        TArray<TSharedPtr<FJsonValue>> Items;
        for (const auto& Item : Value->AsArray())
        {
            Items.Add(CloneValue(Item));
        }
        return MakeShared<FJsonValueArray>(Items);
    }
    return Value;
}

static void SortIdentified(const TSharedPtr<FJsonObject>& Object, const TCHAR* Field, const TCHAR* Identity)
{
    const TArray<TSharedPtr<FJsonValue>>* Original = nullptr;
    if (!Object->TryGetArrayField(Field, Original))
    {
        return;
    }
    TSet<FString> Seen;
    for (const auto& Item : *Original)
    {
        FString Key;
        if (Item->Type != EJson::Object || !Item->AsObject()->TryGetStringField(Identity, Key)
            || Key.IsEmpty() || Seen.Contains(Key))
        {
            return;
        }
        Seen.Add(Key);
    }
    auto Sorted = *Original;
    Sorted.Sort([Identity](const auto& Left, const auto& Right)
    {
        return Left->AsObject()->GetStringField(Identity) < Right->AsObject()->GetStringField(Identity);
    });
    Object->SetArrayField(Field, Sorted);
}

static void NormalizePin(const TSharedPtr<FJsonObject>& Pin)
{
    const TSharedPtr<FJsonObject>* Type = nullptr;
    FString Default;
    FString Auto;
    if (Pin->TryGetObjectField(TEXT("type"), Type)
        && Pin->TryGetStringField(TEXT("default"), Default)
        && Default.IsEmpty() && Pin->TryGetStringField(TEXT("autogenerated"), Auto))
    {
        FString Category;
        (*Type)->TryGetStringField(TEXT("category"), Category);
        const bool bBoolZero = Category == TEXT("bool") && Auto.Equals(TEXT("false"), ESearchCase::IgnoreCase);
        const bool bNumeric = Category == TEXT("real") || Category == TEXT("float") || Category == TEXT("int")
            || Category == TEXT("int64") || Category == TEXT("byte");
        if (bBoolZero || (bNumeric && Auto.IsNumeric() && FCString::Atod(*Auto) == 0.0))
        {
            Pin->SetStringField(TEXT("default"), Auto);
        }
    }
    const TArray<TSharedPtr<FJsonValue>>* Linked = nullptr;
    if (Pin->TryGetArrayField(TEXT("linked"), Linked))
    {
        auto Sorted = *Linked;
        Sorted.Sort([](const auto& Left, const auto& Right)
        {
            return Left->AsString() < Right->AsString();
        });
        Pin->SetArrayField(TEXT("linked"), Sorted);
    }
}

TSharedPtr<FJsonObject> BlueprintRevisionState(const TSharedPtr<FJsonObject>& Raw)
{
    auto Result = CloneValue(MakeShared<FJsonValueObject>(Raw))->AsObject();
    const TSharedPtr<FJsonObject>* Blueprint = nullptr;
    if (!Result->TryGetObjectField(TEXT("blueprint"), Blueprint))
    {
        return Result;
    }
    SortIdentified(*Blueprint, TEXT("graphs"), TEXT("name"));
    const TArray<TSharedPtr<FJsonValue>>* Graphs = nullptr;
    if (!(*Blueprint)->TryGetArrayField(TEXT("graphs"), Graphs))
    {
        return Result;
    }
    for (const auto& GraphValue : *Graphs)
    {
        auto Graph = GraphValue->AsObject();
        const TSharedPtr<FJsonObject>* Signature = nullptr;
        if (Graph->TryGetObjectField(TEXT("signature"), Signature))
        {
            for (const TCHAR* Direction : { TEXT("inputs"), TEXT("outputs") })
            {
                const TArray<TSharedPtr<FJsonValue>>* Parameters = nullptr;
                if ((*Signature)->TryGetArrayField(Direction, Parameters))
                {
                    for (const auto& Parameter : *Parameters)
                    {
                        NormalizePin(Parameter->AsObject());
                    }
                }
            }
        }
        SortIdentified(Graph, TEXT("nodes"), TEXT("guid"));
        const TArray<TSharedPtr<FJsonValue>>* Nodes = nullptr;
        if (!Graph->TryGetArrayField(TEXT("nodes"), Nodes))
        {
            continue;
        }
        for (const auto& NodeValue : *Nodes)
        {
            auto Node = NodeValue->AsObject();
            FString Opaque;
            if (Node->TryGetStringField(TEXT("t3d"), Opaque) && !Opaque.IsEmpty())
            {
                Node->SetStringField(TEXT("t3d"), OpaqueRevisionText(Opaque));
            }
            SortIdentified(Node, TEXT("pins"), TEXT("guid"));
            const TArray<TSharedPtr<FJsonValue>>* Pins = nullptr;
            if (Node->TryGetArrayField(TEXT("pins"), Pins))
            {
                for (const auto& Pin : *Pins)
                {
                    NormalizePin(Pin->AsObject());
                }
            }
        }
    }
    return Result;
}
}
