"""A stable node ID does not make two functions share a pin contract."""

from copy import deepcopy

import pytest

from tests.support.semantics import self_graph_raw
from ue_node_nexus_mcp.transcode.collaboration.merge.engine import merge_snapshots
from ue_node_nexus_mcp.transcode.collaboration.semantic.normalization import normalize_snapshot
from ue_node_nexus_mcp.transcode.collaboration.semantic.snapshot import capture, from_raw, text_of


def call_snapshot(name="Lerp", owner="/Script/Engine.KismetMathLibrary", defaults=None):
    raw = self_graph_raw()
    call = raw["blueprint"]["graphs"][0]["nodes"][1]
    call["config"] = dict(function_owner=owner, function_name=name, self_context="false")
    call["pins"] = [dict(name=key, dir="in", type=dict(category="real", subcategory="double"),
                         default=default, autogenerated=default)
                    for key, default in (defaults or dict(B="1", Alpha="0")).items()]
    return from_raw(raw)


def call_entity(snapshot):
    return next(entity for section in snapshot["semantic"]["sections"].values()
                for entity in section["entities"].values() if entity["type"] == "CallFunction")


@pytest.mark.parametrize("replacement", ["OtherLibrary.Lerp", "KismetMathLibrary.AddFloat"])
@pytest.mark.parametrize("argument", ["", ", B=7"])
def test_replacing_function_drops_old_generated_defaults_in_capture_and_merge(replacement, argument):
    base = call_snapshot()
    source = text_of(base).replace("KismetMathLibrary.Lerp", replacement + argument)
    ours = capture(source, base, "author", "blueprint")
    for snapshot in (ours, normalize_snapshot(ours, base), merge_snapshots(base, ours, base).candidate):
        args = call_entity(snapshot)["args"]
        assert "Alpha" not in args
        assert (args["B"]["value"] == "7") if argument else "B" not in args
        # Reopening a merged workspace must not resurrect the old native pins.
        reopened = capture(text_of(snapshot), snapshot, "author", "blueprint")
        assert call_entity(reopened)["args"] == args


def test_replacement_readback_uses_new_generated_default_and_preserves_real_mismatch():
    base = call_snapshot()
    source = text_of(base).replace("KismetMathLibrary.Lerp", "KismetMathLibrary.AddFloat")
    ours = capture(source, base, "author", "blueprint")
    native = call_snapshot("AddFloat", defaults=dict(B="0"))
    normalized = normalize_snapshot(ours, native)
    call_entity(native)["alias"] = call_entity(ours)["alias"]
    assert call_entity(normalized) == call_entity(native)
    wrong = deepcopy(native)
    call_entity(wrong)["args"]["B"]["value"] = "9"
    assert call_entity(normalized) != call_entity(wrong)


def test_remote_pin_edit_conflicts_with_local_function_replacement():
    base = call_snapshot()
    ours = capture(text_of(base).replace("KismetMathLibrary.Lerp", "KismetMathLibrary.AddFloat"),
                   base, "author", "blueprint")
    theirs = capture(text_of(base).replace("KismetMathLibrary.Lerp", "KismetMathLibrary.Lerp, B=3"),
                     base, "remote", "blueprint")
    assert merge_snapshots(base, ours, theirs).conflicts
