"""Value contracts preserve string content and reflected value identity."""

import pytest

from ue_node_nexus_mcp.transcode.text.semantic import normalize
from ue_node_nexus_mcp.transcode.lint.service import lint_document
from ue_node_nexus_mcp.transcode.text.parser import parse
from ue_node_nexus_mcp.transcode.raw.nodes import pin_default_params


@pytest.mark.parametrize("type_name", ["Object(/Script/Engine.Font)", "object", "UFont*"])
def test_object_null_spellings(type_name):
    assert normalize("None", type_name) == normalize("", type_name)


@pytest.mark.parametrize("text", [" ", "  ", "\t", "None"])
def test_strings_preserve_content(text):
    assert normalize(text, "FString") == text


def test_raw_string_pin_keeps_whitespace_against_empty_autogenerated_value():
    pins = [dict(name="Suffix", dir="in", type=dict(category="string"), default=" ", autogenerated="")]
    assert pin_default_params(pins, set()) == [("Suffix", " ")]


def test_named_color_fields_have_no_order():
    assert normalize("(R=1,G=2,B=3,A=4)", "Color") == normalize("(B=3,G=2,R=1,A=4)", "Color")
    assert normalize("(R=1,G=2,B=3,A=4)", "Color") != normalize("(B=1,G=2,R=3,A=4)", "Color")


def test_static_bool_preview_required():
    document, diagnostics = parse(
        "nexus: 1\nasset: /Game/MF_Test\nclass: MaterialFunction\nschema: key\n"
        "[graph]\nquality : FunctionInput(InputType=FunctionInput_StaticBool, "
        "PreviewValue=(X=0,Y=0,Z=0,W=0), bUsePreviewValueAsDefault=True)\n")
    assert not diagnostics.has_errors
    result = lint_document(document, "material_function", None)
    assert any(item.code == "missing_preview_connection" for item in result.errors())
