#include "NexusBlueprintSignaturePins.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_EditablePinBase.h"
#include "UeNodeNexusBridgeBlueprintPatchHelpers.h"
#include "UeNodeNexusBridgeTranscodeBlueprintApply.h"
#include "UeNodeNexusBridgeTranscodeBlueprintShared.h"

namespace UeNodeNexusBridge::Transcode
{
static TArray<UEdGraphPin*> SignaturePins(UK2Node_EditablePinBase* Node, EEdGraphPinDirection Direction)
{
    TArray<UEdGraphPin*> Result;
    if (Node)
    {
        for (UEdGraphPin* Pin : Node->Pins)
        {
            if (Pin && Pin->Direction == Direction && !Pin->bHidden && Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec)
            {
                Result.Add(Pin);
            }
        }
    }
    return Result;
}

static FString SignatureTypeDefault(UK2Node_EditablePinBase* Node, const FEdGraphPinType& Type)
{
    // Editable pins can overwrite their AutogeneratedDefaultValue with a user
    // value. Query the schema using an unlinked pin that never enters the graph.
    UEdGraphPin* Probe = UEdGraphPin::CreatePin(Node);
    Probe->PinType = Type;
    GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(Probe);
    const FString Result = Probe->GetDefaultAsString();
    Probe->MarkAsGarbage();
    return Result;
}

TArray<TSharedPtr<FJsonValue>> SignaturePinsJson(UK2Node_EditablePinBase* Node, EEdGraphPinDirection Direction)
{
    TArray<TSharedPtr<FJsonValue>> Result;
    for (const UEdGraphPin* Pin : SignaturePins(Node, Direction))
    {
        const TSharedPtr<FUserPinInfo>* User = Node->UserDefinedPins.FindByPredicate([Pin](const TSharedPtr<FUserPinInfo>& Item)
        {
            return Item.IsValid() && Item->PinName == Pin->PinName;
        });
        auto Item = MakeShared<FJsonObject>();
        Item->SetStringField(TEXT("name"), Pin->PinName.ToString());
        Item->SetObjectField(TEXT("type"), PinTypeJson(Pin->PinType));
        Item->SetStringField(TEXT("default"), User ? (*User)->PinDefaultValue : FString());
        Item->SetStringField(TEXT("autogenerated"), SignatureTypeDefault(Node, Pin->PinType));
        Result.Add(MakeShared<FJsonValueObject>(Item));
    }
    return Result;
}

bool SetSignaturePins(UK2Node_EditablePinBase* Node, const TArray<TSharedPtr<FJsonValue>>* Params,
    EEdGraphPinDirection Direction, bool bInherited, FString& Error)
{
    const int32 Count = Params ? Params->Num() : 0;
    TArray<TSharedPtr<FUserPinInfo>> Desired;
    TSet<FName> Names;
    for (int32 Index = 0; Index < Count; ++Index)
    {
        const auto Param = (*Params)[Index].IsValid() ? (*Params)[Index]->AsObject() : nullptr;
        auto Pin = MakeShared<FUserPinInfo>();
        if (!Param.IsValid() || !ReadOpPinType(Param, Pin->PinType, Error))
        {
            Error = Error.IsEmpty() ? TEXT("invalid function parameter") : Error;
            return false;
        }
        Pin->PinName = FName(*ReadOpString(Param, TEXT("name")));
        if (Pin->PinName.IsNone() || Names.Contains(Pin->PinName))
        {
            Error = TEXT("empty or duplicate function parameter: ") + Pin->PinName.ToString();
            return false;
        }
        Names.Add(Pin->PinName);
        Pin->DesiredPinDirection = Direction;
        Pin->PinDefaultValue = ReadOpString(Param, TEXT("default"));
        Desired.Add(Pin);
    }
    if (bInherited)
    {
        const auto Existing = SignaturePins(Node, Direction);
        bool bMatches = Existing.Num() == Desired.Num();
        for (int32 Index = 0; bMatches && Index < Existing.Num(); ++Index)
        {
            bMatches = Existing[Index]->PinName == Desired[Index]->PinName && Existing[Index]->PinType == Desired[Index]->PinType;
        }
        if (!bMatches)
        {
            Error = TEXT("inherited function parameters must match the declaring interface or parent function");
        }
        return bMatches;
    }
    if (!Node)
    {
        return Desired.IsEmpty();
    }
    Node->Modify();
    Node->UserDefinedPins = MoveTemp(Desired);
    // Reconstruction retains matching links and releases removed pins through
    // the engine's graph lifecycle instead of leaving dangling pin pointers.
    const bool bPreviousOrphanPolicy = Node->bDisableOrphanPinSaving;
    Node->bDisableOrphanPinSaving = true;
    Node->ReconstructNode();
    Node->bDisableOrphanPinSaving = bPreviousOrphanPolicy;
    return true;
}
}
