#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "EdGraph/EdGraph.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_FunctionResult.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Serialization/JsonSerializer.h"
#include "UeNodeNexusBridgeTranscodeBlueprintApply.h"
#include "UeNodeNexusBridgeTranscodeBlueprintShared.h"
#include "UObject/Interface.h"

using namespace UeNodeNexusBridge::Transcode;

namespace
{
TSharedPtr<FJsonObject> Json(const TCHAR* Text)
{
    TSharedPtr<FJsonObject> Result;
    FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Text), Result);
    return Result;
}

UBlueprint* Blueprint(bool bInterface = false)
{
    const FName Name = MakeUniqueObjectName(GetTransientPackage(), UBlueprint::StaticClass(), TEXT("NexusSignatureTest"));
    return FKismetEditorUtilities::CreateBlueprint(bInterface ? UInterface::StaticClass() : UObject::StaticClass(),
        GetTransientPackage(), Name, bInterface ? BPTYPE_Interface : BPTYPE_Normal,
        UBlueprint::StaticClass(), UBlueprintGeneratedClass::StaticClass());
}

UEdGraph* Function(UBlueprint* Owner)
{
    UEdGraph* Graph = FBlueprintEditorUtils::CreateNewGraph(Owner, TEXT("Query"), UEdGraph::StaticClass(), UEdGraphSchema_K2::StaticClass());
    FBlueprintEditorUtils::AddFunctionGraph<UClass>(Owner, Graph, true, nullptr);
    return Graph;
}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FNexusSignatureLinks, "Nexus.Issues2.BlueprintSignatureLinks", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FNexusSignatureLinks::RunTest(const FString& Parameters)
{
    UBlueprint* Owner = Blueprint();
    UEdGraph* Graph = Function(Owner);
    FString Error;
    auto Initial = Json(TEXT(R"({"inputs":[{"name":"Value","type":{"category":"real","subcategory":"float"}}],"outputs":[{"name":"Result","type":{"category":"real","subcategory":"float"}}],"flags":["CallInEditor"]})"));
    if (!TestTrue(TEXT("signature is created"), ApplyBlueprintFunctionSignature(Graph, Initial, Error)))
    {
        AddError(Error);
        return false;
    }
    TArray<UK2Node_FunctionEntry*> Entries;
    Graph->GetNodesOfClass(Entries);
    UK2Node_FunctionResult* Result = FBlueprintEditorUtils::FindOrCreateFunctionResultNode(Entries[0]);
    const auto* Schema = GetDefault<UEdGraphSchema_K2>();
    TestTrue(TEXT("result is wired"), Schema->TryCreateConnection(Entries[0]->FindPin(TEXT("Value")), Result->FindPin(TEXT("Result"))));
    auto Changed = Json(TEXT(R"({"inputs":[{"name":"Value","type":{"category":"real","subcategory":"float"}},{"name":"Label","type":{"category":"string"}}],"outputs":[{"name":"Result","type":{"category":"real","subcategory":"float"}}],"flags":[]})"));
    TestTrue(TEXT("signature can grow"), ApplyBlueprintFunctionSignature(Graph, Changed, Error));
    TestTrue(TEXT("existing data link survives"), Result->FindPin(TEXT("Result"))->LinkedTo.Contains(Entries[0]->FindPin(TEXT("Value"))));
    TestFalse(TEXT("CallInEditor can be cleared"), Entries[0]->MetaData.bCallInEditor);
    auto Empty = Json(TEXT(R"({"inputs":[],"outputs":[],"flags":[]})"));
    TestTrue(TEXT("parameters can be removed"), ApplyBlueprintFunctionSignature(Graph, Empty, Error));
    TestNull(TEXT("removed return pin is absent"), Result->FindPin(TEXT("Result")));
    return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FNexusInterfaceSignature, "Nexus.Issues2.BlueprintInterfaceSignature", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FNexusInterfaceSignature::RunTest(const FString& Parameters)
{
    UBlueprint* Interface = Blueprint(true);
    UEdGraph* Declaration = Function(Interface);
    auto Signature = Json(TEXT(R"({"inputs":[],"outputs":[{"name":"Result","type":{"category":"real","subcategory":"float"}}],"flags":[]})"));
    FString Error;
    if (!TestTrue(TEXT("interface return is declared"), ApplyBlueprintFunctionSignature(Declaration, Signature, Error)))
    {
        AddError(Error);
        return false;
    }
    FKismetEditorUtilities::CompileBlueprint(Interface);
    const auto Declared = FunctionSignatureJson(Declaration)->GetArrayField(TEXT("outputs"))[0]->AsObject();
    TestEqual(TEXT("generated return default is exported"), Declared->GetStringField(TEXT("autogenerated")), FString(TEXT("0.0")));
    UBlueprint* Owner = Blueprint();
    if (!TestTrue(TEXT("interface is implemented"), FBlueprintEditorUtils::ImplementNewInterface(Owner, Interface->GeneratedClass->GetClassPathName())))
    {
        return false;
    }
    UEdGraph* Graph = Owner->ImplementedInterfaces[0].Graphs[0];
    TestTrue(TEXT("implementation accepts its declared signature"), ApplyBlueprintFunctionSignature(Graph, Signature, Error));
    const auto Export = FunctionSignatureJson(Graph);
    const auto& Outputs = Export->GetArrayField(TEXT("outputs"));
    if (TestEqual(TEXT("one return is exported"), Outputs.Num(), 1))
    {
        TestEqual(TEXT("return name is preserved"), Outputs[0]->AsObject()->GetStringField(TEXT("name")), FString(TEXT("Result")));
    }
    auto Wrong = Json(TEXT(R"({"inputs":[],"outputs":[{"name":"Other","type":{"category":"real","subcategory":"float"}}],"flags":[]})"));
    TestFalse(TEXT("implementation cannot rename an inherited return"), ApplyBlueprintFunctionSignature(Graph, Wrong, Error));
    Error.Reset();
    const auto WithDefault = Json(TEXT(R"({"inputs":[],"outputs":[{"name":"Result","type":{"category":"real","subcategory":"float"},"default":"7"}],"flags":[]})"));
    TestTrue(TEXT("a function default can be edited"), ApplyBlueprintFunctionSignature(Declaration, WithDefault, Error));
    const auto Edited = FunctionSignatureJson(Declaration)->GetArrayField(TEXT("outputs"))[0]->AsObject();
    TestEqual(TEXT("user default remains distinct from type default"), Edited->GetStringField(TEXT("autogenerated")), FString(TEXT("0.0")));
    TestTrue(TEXT("user value is exported"), FCString::Atof(*Edited->GetStringField(TEXT("default"))) == 7.0f);
    return true;
}

#endif
