"""Blueprint graph nodes: raw node -> Decl, raw links -> Link.

Raw node shape::

    {"guid", "class", "class_short", "x", "y", "title", "enabled": true, "comment": "",
     "config": {"function_owner", "function_name", "self_context", "variable_name",
                "event_name", "macro_owner", "macro_name", "target_type", "struct_type",
                "input_key", "input_action_name", "input_axis_name", "input_action",
                "dynamic_pins"},
     "props": [{"name","type","value","default"}],
     "pins": [{"guid","name","dir":"in|out","type":{...},"default","autogenerated","hidden","linked":[pin guids]}],
     "supported": true, "t3d": ""}
"""

from __future__ import annotations

from typing import Any

from .bp_types import is_zero_default, type_text
from .ids import IdAllocator, blueprint_node_candidate, short_class_name
from .model import Decl, Link
from .raw_common import non_default_params, prop_defaults, prop_types, prop_values
from .values import values_equal

EXEC_CATEGORY = "exec"
_CLASS_POSITIONAL = {
    "CallFunction": "function",
    "CallParentFunction": "function",
    "Message": "function",
    "PromotableOperator": "function",
    "CommutativeAssociativeBinaryOperator": "function",
    "Event": "function",
    "CustomEvent": "event",
    "VariableGet": "variable",
    "VariableSet": "variable",
    "MacroInstance": "macro",
    "DynamicCast": "target_type",
    "ClassDynamicCast": "target_type",
    "MakeStruct": "struct_type",
    "BreakStruct": "struct_type",
    "SetFieldsInStruct": "struct_type",
    "InputKey": "input_key",
    "InputAction": "input_action_name",
    "InputAxisEvent": "input_axis_name",
    "EnhancedInputAction": "input_action",
}


def owner_label(path: str) -> str:
    """``/Script/Engine.KismetSystemLibrary`` -> ``KismetSystemLibrary``; asset paths stay full."""
    if path.startswith("/Script/"):
        return path.rsplit(".", 1)[-1]
    return path


def positional_args(class_short: str, config: dict[str, Any], pins: list[dict[str, Any]]) -> list[str]:
    kind = _CLASS_POSITIONAL.get(class_short)
    if kind is None:
        return []
    if kind == "function":
        owner = str(config.get("function_owner", ""))
        name = str(config.get("function_name", ""))
        if str(config.get("self_context", "")).lower() == "true":
            return [f"self.{name}"]
        return [f"{owner_label(owner)}.{name}" if owner else name]
    if kind == "event":
        params = [f"{pin['name']}: {type_text(pin.get('type'))}" for pin in pins if pin.get("dir") == "out" and _is_data_pin(pin)]
        return [str(config.get("event_name", "")), *params]
    if kind == "variable":
        owner = str(config.get("variable_owner", ""))
        name = str(config.get("variable_name", ""))
        if owner and str(config.get("self_context", "true")).lower() != "true":
            return [f"{owner_label(owner)}.{name}"]
        return [name]
    if kind == "macro":
        owner = str(config.get("macro_owner", ""))
        name = str(config.get("macro_name", ""))
        return [f"{owner.rsplit('/', 1)[-1].split('.')[0]}.{name}" if owner else name]
    value = str(config.get(kind, ""))
    return [value] if value else []


def _is_data_pin(pin: dict[str, Any]) -> bool:
    pin_type = pin.get("type") or {}
    return str(pin_type.get("category", "")) not in (EXEC_CATEGORY, "delegate", "mcdelegate") and not pin.get("hidden")


def pin_default_params(pins: list[dict[str, Any]], prop_names: set[str]) -> list[tuple[str, str]]:
    params: list[tuple[str, str]] = []
    for pin in pins:
        if pin.get("dir") != "in" or not _is_data_pin(pin) or pin.get("linked"):
            continue
        default = str(pin.get("default", ""))
        autogenerated = pin.get("autogenerated")
        if autogenerated is not None and values_equal(default, str(autogenerated)):
            continue
        if autogenerated in (None, "") and is_zero_default(default, type_text(pin.get("type")).rstrip("&")):
            continue
        name = str(pin.get("name", ""))
        params.append((f"pin:{name}" if name in prop_names else name, default))
    return params


def node_decl(identifier: str, node: dict[str, Any]) -> Decl:
    class_short = str(node.get("class_short") or short_class_name(str(node.get("class", ""))))
    config = dict(node.get("config") or {})
    pins = list(node.get("pins") or [])
    position = (int(node.get("x", 0)), int(node.get("y", 0)))
    meta = {
        "guid": str(node.get("guid", "")),
        "class": str(node.get("class", "")),
        "class_short": class_short,
        "config": config,
        "pins": pins,
        "pin_names": [str(pin.get("name", "")) for pin in pins],
        "prop_types": prop_types(node.get("props")),
        "prop_defaults": prop_defaults(node.get("props")),
        "prop_values": prop_values(node.get("props")),
        "supported": bool(node.get("supported", True)),
    }
    decl = Decl(id=identifier, type_name=class_short, pos=position, meta=meta)
    if not node.get("supported", True):
        decl.type_name = "@opaque"
        decl.args = [(None, str(node.get("class", "")))]
    else:
        args: list[tuple[str | None, str]] = [(None, value) for value in positional_args(class_short, config, pins)]
        dynamic = config.get("dynamic_pins")
        if dynamic not in (None, ""):
            args.append(("pins", str(dynamic)))
        pin_names = set(meta["pin_names"])
        prop_names = set(meta["prop_types"])
        args.extend(pin_default_params(pins, prop_names))
        for key, value in non_default_params(node.get("props")):
            args.append((f"prop:{key}" if key in pin_names else key, value))
        decl.args = args
    if str(node.get("enabled", "true")).lower() == "false" or node.get("enabled") is False:
        decl.flags.append("disabled")
    comment = str(node.get("comment", "") or "")
    if comment:
        decl.annotations["comment"] = comment
    return decl


def assign_node_ids(nodes: list[dict[str, Any]], allocator: IdAllocator) -> dict[str, str]:
    ids: dict[str, str] = {}
    for node in nodes:
        guid = str(node.get("guid", ""))
        if guid in allocator.by_guid:
            ids[guid] = allocator.allocate(guid, "")
    for node in nodes:
        guid = str(node.get("guid", ""))
        if guid in ids:
            continue
        class_short = str(node.get("class_short") or short_class_name(str(node.get("class", ""))))
        if class_short == "FunctionEntry":
            ids[guid] = allocator.allocate(guid, "entry")
            continue
        if class_short == "FunctionResult":
            ids[guid] = allocator.allocate(guid, "result")
            continue
        candidate = blueprint_node_candidate(class_short, dict(node.get("config") or {}), str(node.get("title", "")))
        ids[guid] = allocator.allocate(guid, candidate, class_short)
    return ids


def pin_name_by_guid(nodes: list[dict[str, Any]]) -> dict[str, tuple[str, str]]:
    """pin guid -> (node guid, pin name)."""
    result: dict[str, tuple[str, str]] = {}
    for node in nodes:
        node_guid = str(node.get("guid", ""))
        for pin in node.get("pins") or []:
            result[str(pin.get("guid", ""))] = (node_guid, str(pin.get("name", "")))
    return result


def single_visible_pin(node: dict[str, Any], direction: str) -> str | None:
    """Name of the only visible data pin in ``direction`` (so links may omit it).

    Exec pins and opaque nodes always keep explicit pin names.
    """
    if not node.get("supported", True):
        return None
    visible = [pin for pin in node.get("pins") or [] if pin.get("dir") == direction and not pin.get("hidden")]
    if len(visible) != 1 or not _is_data_pin(visible[0]):
        return None
    return str(visible[0].get("name", ""))


def build_links(graph: dict[str, Any], ids: dict[str, str]) -> tuple[list[Link], dict[str, set[str]]]:
    nodes = list(graph.get("nodes") or [])
    by_guid = {str(node.get("guid", "")): node for node in nodes}
    links: list[Link] = []
    depends_on: dict[str, set[str]] = {}
    seen: set[tuple[str, str, str, str]] = set()
    pins = pin_name_by_guid(nodes)
    for node in nodes:
        node_guid = str(node.get("guid", ""))
        for pin in node.get("pins") or []:
            for linked in pin.get("linked") or []:
                other = pins.get(str(linked))
                if other is None or other[0] not in ids or node_guid not in ids:
                    continue
                if pin.get("dir") == "out":
                    key = (ids[node_guid], str(pin.get("name", "")), ids[other[0]], other[1])
                    src_node, dst_node = node, by_guid[other[0]]
                else:
                    key = (ids[other[0]], other[1], ids[node_guid], str(pin.get("name", "")))
                    src_node, dst_node = by_guid[other[0]], node
                if key in seen:
                    continue
                seen.add(key)
                depends_on.setdefault(key[2], set()).add(key[0])
                src_pin = None if single_visible_pin(src_node, "out") == key[1] else key[1]
                dst_pin = None if single_visible_pin(dst_node, "in") == key[3] else key[3]
                links.append(Link(key[0], src_pin, key[2], dst_pin))
    return links, depends_on
