"""Blueprint reference spellings and effective input defaults used by the mirror."""

from ...blueprint.classes import node_name
from ...blueprint.signature import KNOWN_FLAGS, parse_signature
from ...blueprint.types import is_zero_default, join_type_text, parse_type_text, type_text
from ...text.lexer import LexError
from ...raw.nodes import owner_label
from ...errors import SyncError
from ...schema.functions import reference as function_reference
from ...text.semantic import normalize, value

FUNCTION_NODES = set(("CallFunction", "CallParentFunction", "Message", "Event"))


def declaration_default(decl, kind, section, class_name):
    text = decl.default
    if kind == "blueprint" and (section == "variables" or decl.modifier == "local"):
        full_type = join_type_text(decl.type_name, decl.args)
        if text is not None and is_zero_default(text, full_type):
            text = None
        return value(text, full_type)
    return value(text, class_name)


def positional_values(decl, family, metadata=None, schema=None):
    positional = decl.positional()
    if family == "k2node" and node_name(decl.type_name) in FUNCTION_NODES and positional:
        owner, separator, name = positional[0].rpartition(".")
        if separator:
            config = (metadata if metadata is not None else decl.meta).get("config", dict())
            native_owner = str(config.get("function_owner", ""))
            same_owner = owner == native_owner or (not owner.startswith("/") and owner == owner_label(native_owner))
            self_context = str(config.get("self_context", "")).lower() == "true"
            if config.get("function_name") == name and same_owner:
                owner = "self" if self_context else native_owner
            positional[0] = function_reference(schema, owner, name)
    return positional


def input_metadata(metadata, types, defaults):
    """Use generated defaults, never the value written by the current apply."""
    pins = metadata.get("pins", [])
    names = set(pin["name"] for pin in pins)
    props = set(metadata.get("prop_types", dict()))
    for name in props & names:
        if name in types:
            types["prop:" + name] = types.pop(name)
        if name in defaults:
            defaults["prop:" + name] = defaults.pop(name)
    for pin in pins:
        if pin.get("dir") != "in" or pin.get("hidden"):
            continue
        kind = pin.get("type") or dict()
        if kind.get("category") in ("exec", "delegate", "mcdelegate"):
            continue
        name = ("pin:" if pin["name"] in props else "") + pin["name"]
        types[name] = pin.get("value_schema") or type_text(kind)
        if pin.get("autogenerated") is not None:
            defaults[name] = pin["autogenerated"]


def signature_contracts(raw):
    blueprint = (raw or dict()).get("blueprint", dict())
    result = dict(("function:" + graph["name"], graph.get("signature", dict()))
                  for graph in blueprint.get("graphs", []) if graph.get("kind") == "function")
    result.update(("dispatcher:" + row["name"], dict(inputs=row.get("params", [])))
                  for row in blueprint.get("dispatchers", []))
    return result


def signature(text, line, *, function=False, contracts=None):
    try:
        parsed = parse_signature(text)
        if function and not set(parsed.flags) & set(("Public", "Protected", "Private")):
            parsed.flags.append("Public")
        parsed.flags = sorted(set(parsed.flags), key=lambda flag: (KNOWN_FLAGS.index(flag) if flag in KNOWN_FLAGS else len(KNOWN_FLAGS), flag))
        contract = (contracts or dict()).get(("function:" if function else "dispatcher:") + parsed.name, dict())
        for direction in ("inputs", "outputs"):
            generated = dict((item["name"], item) for item in contract.get(direction, []))
            for parameter in getattr(parsed, direction):
                parameter.type_text = type_text(parse_type_text(parameter.type_text))
                if parameter.default is not None:
                    parameter.default = normalize(parameter.default, parameter.type_text)
                native = generated.get(parameter.name, dict())
                if "autogenerated" in native and type_text(native.get("type")) == parameter.type_text:
                    if parameter.default == normalize(native["autogenerated"], parameter.type_text):
                        parameter.default = None
        return parsed
    except LexError as error:
        raise SyncError("invalid_signature", str(error), dict(line=line, col=error.col)) from error
