"""Shared fixtures used across the regression suites."""

from tests.support.semantics import self_graph_raw


def branch_raw():
    raw = self_graph_raw()
    node = dict(guid="BRANCH", class_short="IfThenElse", supported=True, x=0, y=0, config=dict(), props=[],
                pins=[dict(guid="CONDITION", name="Condition", dir="in", type=dict(category="bool"),
                           default="True", autogenerated="true", linked=[])])
    raw["blueprint"]["graphs"][0]["nodes"] = [node]
    return raw
