#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "UeNodeNexusCollaboration.h"
#include "Transcode/Revision/NexusOpaqueRevision.h"
#include "Misc/CommandLine.h"
#include "Misc/FileHelper.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"

using namespace UeNodeNexusBridge::Collaboration;

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FNexusBlueprintRevisionTests,
    "Nexus.Issues3.Recovery.BlueprintRevision",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

static FJson ParseRevisionJson(const FString& Text)
{
    FJson Result;
    FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Text), Result);
    return Result;
}

bool FNexusBlueprintRevisionTests::RunTest(const FString& Parameters)
{
    const FString Original = TEXT(R"({"kind":"blueprint","blueprint":{"graphs":[{"name":"EventGraph","nodes":[{"guid":"node","pins":[{"guid":"b","type":{"category":"bool"},"default":"","autogenerated":"false","linked":[]},{"guid":"a","type":{"category":"string"},"default":" ","autogenerated":"","linked":[]}]}]}]}})");
    const FString Reordered = TEXT(R"({"kind":"blueprint","blueprint":{"graphs":[{"name":"EventGraph","nodes":[{"guid":"node","pins":[{"guid":"a","type":{"category":"string"},"default":" ","autogenerated":"","linked":[]},{"guid":"b","type":{"category":"bool"},"default":"false","autogenerated":"false","linked":[]}]}]}]}})");
    auto Before = StampRaw(ParseRevisionJson(Original));
    auto After = StampRaw(ParseRevisionJson(Reordered));
    TestEqual(TEXT("pin order and implicit bool zero preserve revision"),
        Before->GetStringField(TEXT("content_revision")), After->GetStringField(TEXT("content_revision")));
    auto Changed = StampRaw(ParseRevisionJson(Reordered.Replace(TEXT("\"default\":\" \""), TEXT("\"default\":\"\""))));
    TestNotEqual(TEXT("string whitespace still changes revision"),
        Before->GetStringField(TEXT("content_revision")), Changed->GetStringField(TEXT("content_revision")));

    const FString Opaque = TEXT("Begin Object Name=\"Node\"\nValue=0.700000\nLabel=\" \"\nNodeGuid=ABC\nLinkedTo(0)=Peer.Pin\nEnd Object");
    const FString Canonical = OpaqueRevisionText(Opaque);
    TestEqual(TEXT("opaque numeric formatting is stable"), Canonical,
        OpaqueRevisionText(Opaque.Replace(TEXT("0.700000"), TEXT("0.7"))));
    for (const auto& Pair : TArray<TPair<FString, FString>>
        {
            { TEXT("0.700000"), TEXT("0.8") },
            { TEXT("Label=\" \""), TEXT("Label=\"\"") },
            { TEXT("NodeGuid=ABC"), TEXT("NodeGuid=ABD") },
            { TEXT("Peer.Pin"), TEXT("Other.Pin") }
        })
    {
        TestNotEqual(TEXT("opaque writable change retained: ") + Pair.Key, Canonical,
            OpaqueRevisionText(Opaque.Replace(*Pair.Key, *Pair.Value)));
    }

    FString Directory;
    if (FParse::Value(FCommandLine::Get(), TEXT("NexusIssues3Receipts="), Directory))
    {
        for (const TCHAR* Name : { TEXT("animation"), TEXT("outline"), TEXT("shadow") })
        {
            FString Text;
            const FString File = FPaths::Combine(Directory, FString(Name) + TEXT(".json"));
            if (!TestTrue(TEXT("captured receipt readable: ") + File, FFileHelper::LoadFileToString(Text, *File)))
            {
                continue;
            }
            const auto Receipt = ParseRevisionJson(Text);
            const FJson* CapturedBefore = nullptr;
            const FJson* Restored = nullptr;
            if (!Receipt.IsValid() || !Receipt->TryGetObjectField(TEXT("before"), CapturedBefore)
                || !Receipt->TryGetObjectField(TEXT("recovery_observation"), Restored))
            {
                AddError(TEXT("receipt has no restoration evidence: ") + File);
                continue;
            }
            TestEqual(FString(Name) + TEXT(" restored native revision"),
                StampRaw(*CapturedBefore)->GetStringField(TEXT("content_revision")),
                StampRaw(*Restored)->GetStringField(TEXT("content_revision")));
        }
    }
    return true;
}

#endif
