#include "UeNodeNexusBridgeTranscode.h"
#include "UeNodeNexusBridgeTranscodeBlueprintApply.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "Blueprint/NexusBlueprintPinNames.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "K2Node_AddPinInterface.h"
#include "K2Node_ExecutionSequence.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_FunctionResult.h"
#include "UeNodeNexusBridgeBlueprintPatchHelpers.h"
#include "UeNodeNexusBridgeObjectHelpers.h"

namespace UeNodeNexusBridge::Transcode
{
FString ReadOpString(const TSharedPtr<FJsonObject>& Op, const TCHAR* Field, const FString& Default)
{
    FString Value;
    return Op->TryGetStringField(Field, Value) ? Value : Default;
}

UEdGraphNode* ResolveGraphNode(UBlueprint* Blueprint, UEdGraph* Graph, const FApplyContext& Context, const FString& LocalId)
{
    if (const FString* Guid = Context.Ids.Find(LocalId))
    {
        if (UEdGraphNode* Node = FindBlueprintNode(Graph, *Guid))
        {
            return Node;
        }
    }
    if (LocalId == TEXT("entry") || LocalId == TEXT("result"))
    {
        for (UEdGraphNode* Node : Graph->Nodes)
        {
            if ((LocalId == TEXT("entry") && Cast<UK2Node_FunctionEntry>(Node)) || (LocalId == TEXT("result") && Cast<UK2Node_FunctionResult>(Node)))
            {
                return Node;
            }
        }
    }
    return nullptr;
}

UEdGraphPin* ResolvePin(UEdGraphNode* Node, const FString& PinName, EEdGraphPinDirection Direction)
{
    if (Node == nullptr)
    {
        return nullptr;
    }
    if (PinName.IsEmpty())
    {
        UEdGraphPin* Single = nullptr;
        int32 Count = 0;
        for (UEdGraphPin* Pin : Node->Pins)
        {
            if (Pin && Pin->Direction == Direction && !Pin->bHidden && Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec)
            {
                Single = Pin;
                ++Count;
            }
        }
        return Count == 1 ? Single : nullptr;
    }
    if (UEdGraphPin* Aliased = FindAliasedPin(Node, PinName, Direction))
    {
        return Aliased;
    }
    for (UEdGraphPin* Pin : Node->Pins)
    {
        if (Pin && Pin->Direction == Direction && Pin->PinName.ToString().Equals(PinName, ESearchCase::IgnoreCase))
        {
            return Pin;
        }
    }
    for (UEdGraphPin* Pin : Node->Pins)
    {
        if (Pin && Pin->Direction == Direction && Pin->GetDisplayName().ToString().Equals(PinName, ESearchCase::IgnoreCase))
        {
            return Pin;
        }
    }
    return nullptr;
}

static bool SetPinDefault(UEdGraph* Graph, UEdGraphPin* Pin, const TSharedPtr<FJsonValue>& Value, FString& OutError)
{
    const UEdGraphSchema* Schema = Graph->GetSchema();
    Pin->Modify();
    if (!Value.IsValid() || Value->IsNull())
    {
        Schema->ResetPinToAutogeneratedDefaultValue(Pin, true);
        return true;
    }
    FString Text;
    if (!Value->TryGetString(Text))
    {
        Text = JsonValueToImportText(Value);
    }
    const FName Category = Pin->PinType.PinCategory;
    if (Category == UEdGraphSchema_K2::PC_Object || Category == UEdGraphSchema_K2::PC_Class || Category == UEdGraphSchema_K2::PC_Interface)
    {
        UObject* Object = Text.IsEmpty() || Text == TEXT("None") ? nullptr : ResolveObjectByPath(Text);
        if (Object == nullptr && !Text.IsEmpty() && Text != TEXT("None"))
        {
            OutError = FString::Printf(TEXT("object not found for pin %s: %s"), *Pin->PinName.ToString(), *Text);
            return false;
        }
        Schema->TrySetDefaultObject(*Pin, Object, true);
        return true;
    }
    if (Category == UEdGraphSchema_K2::PC_Text)
    {
        Schema->TrySetDefaultText(*Pin, FText::FromString(Text), true);
        return true;
    }
    Schema->TrySetDefaultValue(*Pin, Text, true);
    return true;
}

bool SetNodeParam(UBlueprint* Blueprint, UEdGraph* Graph, UEdGraphNode* Node, const FString& RawName, const TSharedPtr<FJsonValue>& Value, FString& OutError)
{
    FString Name = RawName;
    bool bForcePin = false;
    bool bForceProp = false;
    if (Name.RemoveFromStart(TEXT("pin:")))
    {
        bForcePin = true;
    }
    else if (Name.RemoveFromStart(TEXT("prop:")))
    {
        bForceProp = true;
    }
    if (Name == TEXT("pins"))
    {
        return true;
    }
    if (!bForceProp)
    {
        if (UEdGraphPin* Pin = ResolvePin(Node, Name, EGPD_Input))
        {
            if (Pin->LinkedTo.Num() > 0)
            {
                OutError = FString::Printf(TEXT("pin %s is linked; defaults only apply to unlinked pins"), *Name);
                return false;
            }
            return SetPinDefault(Graph, Pin, Value, OutError);
        }
        if (bForcePin)
        {
            OutError = FString::Printf(TEXT("pin not found: %s"), *Name);
            return false;
        }
    }
    FString Text;
    if (!Value.IsValid() || Value->IsNull())
    {
        FProperty* Property = Node->GetClass()->FindPropertyByName(FName(*Name));
        if (Property == nullptr)
        {
            OutError = FString::Printf(TEXT("neither a pin nor a property: %s"), *Name);
            return false;
        }
        Text = ExportPropertyValue(Node->GetClass()->GetDefaultObject(), Property);
    }
    else if (!Value->TryGetString(Text))
    {
        Text = JsonValueToImportText(Value);
    }
    if (!ImportPropertyValue(Node, Name, Text, OutError))
    {
        return false;
    }
    Node->ReconstructNode();
    return true;
}

static bool IsDynamicPin(UEdGraphNode* Node, UEdGraphPin* Pin)
{
    if (Pin == nullptr || Pin->bHidden)
    {
        return false;
    }
    if (Cast<UK2Node_ExecutionSequence>(Node))
    {
        return Pin->Direction == EGPD_Output && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
    }
    return Pin->Direction == EGPD_Input && Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec && Pin->PinName != UEdGraphSchema_K2::PN_Self;
}

static int32 CountDynamicPins(UEdGraphNode* Node)
{
    int32 Count = 0;
    for (UEdGraphPin* Pin : Node->Pins)
    {
        Count += IsDynamicPin(Node, Pin) ? 1 : 0;
    }
    return Count;
}

bool SetDynamicPins(UEdGraphNode* Node, int32 Count, FString& OutError)
{
    IK2Node_AddPinInterface* AddPin = Cast<IK2Node_AddPinInterface>(Node);
    if (AddPin == nullptr)
    {
        OutError = FString::Printf(TEXT("%s does not support pins=N"), *Node->GetClass()->GetName());
        return false;
    }
    int32 Guard = 64;
    while (CountDynamicPins(Node) < Count && Guard-- > 0)
    {
        AddPin->AddInputPin();
    }
    while (CountDynamicPins(Node) > Count && Guard-- > 0)
    {
        UEdGraphPin* Last = nullptr;
        for (UEdGraphPin* Pin : Node->Pins)
        {
            if (IsDynamicPin(Node, Pin))
            {
                Last = Pin;
            }
        }
        if (Last == nullptr || !AddPin->CanRemovePin(Last))
        {
            break;
        }
        AddPin->RemoveInputPin(Last);
    }
    return true;
}
}
