#include "UeNodeNexusBridgeTranscode.h"
#include "UeNodeNexusBridgeTranscodeBlueprintShared.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraphUtilities.h"
#include "Engine/Blueprint.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_FunctionResult.h"
#include "Blueprint/UeNodeNexusBridgeBlueprintPinDefaults.h"

namespace UeNodeNexusBridge::Transcode
{
static const TCHAR* GSupportedNodeClasses[] = {
    TEXT("K2Node_CallFunction"), TEXT("K2Node_CallParentFunction"), TEXT("K2Node_Message"), TEXT("K2Node_CommutativeAssociativeBinaryOperator"),
    TEXT("K2Node_PromotableOperator"), TEXT("K2Node_Event"), TEXT("K2Node_CustomEvent"), TEXT("K2Node_VariableGet"), TEXT("K2Node_VariableSet"),
    TEXT("K2Node_IfThenElse"), TEXT("K2Node_ExecutionSequence"), TEXT("K2Node_Knot"), TEXT("EdGraphNode_Comment"), TEXT("K2Node_Select"),
    TEXT("K2Node_DynamicCast"), TEXT("K2Node_ClassDynamicCast"), TEXT("K2Node_SpawnActorFromClass"), TEXT("K2Node_MakeStruct"),
    TEXT("K2Node_BreakStruct"), TEXT("K2Node_SetFieldsInStruct"), TEXT("K2Node_MakeArray"), TEXT("K2Node_GetArrayItem"), TEXT("K2Node_Self"),
    TEXT("K2Node_MacroInstance"), TEXT("K2Node_InputKey"), TEXT("K2Node_InputAction"), TEXT("K2Node_InputAxisEvent"), TEXT("K2Node_EnhancedInputAction"),
    TEXT("K2Node_FunctionEntry"), TEXT("K2Node_FunctionResult"), TEXT("K2Node_SwitchInteger"), TEXT("K2Node_SwitchString"), TEXT("K2Node_SwitchName"),
    TEXT("K2Node_SwitchEnum"), TEXT("K2Node_Literal"),
};

bool IsSupportedNodeClass(const UClass* Class)
{
    if (Class == nullptr)
    {
        return false;
    }
    const FString Name = Class->GetName();
    for (const TCHAR* Supported : GSupportedNodeClasses)
    {
        if (Name == Supported)
        {
            return true;
        }
    }
    return false;
}

static TSharedPtr<FJsonObject> PinJson(const UEdGraphPin* Pin)
{
    TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
    Json->SetStringField(TEXT("guid"), Pin->PinId.ToString(EGuidFormats::DigitsWithHyphens));
    Json->SetStringField(TEXT("name"), Pin->PinName.ToString());
    Json->SetStringField(TEXT("dir"), Pin->Direction == EGPD_Input ? TEXT("in") : TEXT("out"));
    Json->SetObjectField(TEXT("type"), PinTypeJson(Pin->PinType));
    Json->SetStringField(TEXT("default"), BlueprintPinDefaultText(Pin));
    Json->SetStringField(TEXT("autogenerated"), Pin->AutogeneratedDefaultValue);
    Json->SetBoolField(TEXT("hidden"), Pin->bHidden);
    TArray<TSharedPtr<FJsonValue>> Linked;
    for (const UEdGraphPin* Other : Pin->LinkedTo)
    {
        if (Other != nullptr)
        {
            Linked.Add(MakeShared<FJsonValueString>(Other->PinId.ToString(EGuidFormats::DigitsWithHyphens)));
        }
    }
    Json->SetArrayField(TEXT("linked"), Linked);
    return Json;
}

TSharedPtr<FJsonObject> NodeJson(UBlueprint* Blueprint, UEdGraphNode* Node, bool bForceOpaque)
{
    TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
    Json->SetStringField(TEXT("guid"), Node->NodeGuid.ToString(EGuidFormats::DigitsWithHyphens));
    Json->SetStringField(TEXT("class"), Node->GetClass()->GetPathName());
    FString Short = Node->GetClass()->GetName();
    Short.RemoveFromStart(TEXT("K2Node_"));
    Short.RemoveFromStart(TEXT("EdGraphNode_"));
    Json->SetStringField(TEXT("class_short"), Short);
    Json->SetNumberField(TEXT("x"), Node->NodePosX);
    Json->SetNumberField(TEXT("y"), Node->NodePosY);
    Json->SetStringField(TEXT("title"), Node->GetNodeTitle(ENodeTitleType::ListView).ToString());
    Json->SetBoolField(TEXT("enabled"), Node->GetDesiredEnabledState() != ENodeEnabledState::Disabled);
    Json->SetStringField(TEXT("comment"), Node->NodeComment);
    Json->SetObjectField(TEXT("config"), NodeConfigJson(Blueprint, Node));
    Json->SetArrayField(TEXT("props"), ExportEditableProps(Node));
    TArray<TSharedPtr<FJsonValue>> Pins;
    for (UEdGraphPin* Pin : Node->Pins)
    {
        if (Pin != nullptr)
        {
            Pins.Add(MakeShared<FJsonValueObject>(PinJson(Pin)));
        }
    }
    Json->SetArrayField(TEXT("pins"), Pins);
    const bool bSupported = !bForceOpaque && IsSupportedNodeClass(Node->GetClass());
    Json->SetBoolField(TEXT("supported"), bSupported);
    if (!bSupported)
    {
        FString Text;
        TSet<UObject*> Objects;
        Objects.Add(Node);
        FEdGraphUtilities::ExportNodesToText(Objects, Text);
        Json->SetStringField(TEXT("t3d"), Text);
    }
    return Json;
}

TArray<TSharedPtr<FJsonValue>> UserPinsJson(UK2Node_EditablePinBase* Node)
{
    TArray<TSharedPtr<FJsonValue>> Params;
    if (Node == nullptr)
    {
        return Params;
    }
    for (const TSharedPtr<FUserPinInfo>& Pin : Node->UserDefinedPins)
    {
        if (!Pin.IsValid())
        {
            continue;
        }
        TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
        Json->SetStringField(TEXT("name"), Pin->PinName.ToString());
        Json->SetObjectField(TEXT("type"), PinTypeJson(Pin->PinType));
        Json->SetStringField(TEXT("default"), Pin->PinDefaultValue);
        Params.Add(MakeShared<FJsonValueObject>(Json));
    }
    return Params;
}

TSharedPtr<FJsonObject> FunctionSignatureJson(UEdGraph* Graph)
{
    TSharedPtr<FJsonObject> Signature = MakeShared<FJsonObject>();
    TArray<UK2Node_FunctionEntry*> Entries;
    Graph->GetNodesOfClass(Entries);
    TArray<UK2Node_FunctionResult*> Results;
    Graph->GetNodesOfClass(Results);
    UK2Node_FunctionEntry* Entry = Entries.Num() > 0 ? Entries[0] : nullptr;
    Signature->SetArrayField(TEXT("inputs"), UserPinsJson(Entry));
    Signature->SetArrayField(TEXT("outputs"), UserPinsJson(Results.Num() > 0 ? Results[0] : nullptr));
    TArray<TSharedPtr<FJsonValue>> Flags;
    TArray<TSharedPtr<FJsonValue>> Locals;
    FString Category;
    if (Entry != nullptr)
    {
        const int32 FunctionFlags = Entry->GetFunctionFlags();
        if (FunctionFlags & FUNC_BlueprintPure)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Pure")));
        }
        if (FunctionFlags & FUNC_Const)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Const")));
        }
        if (FunctionFlags & FUNC_Static)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Static")));
        }
        if (FunctionFlags & FUNC_Protected)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Protected")));
        }
        else if (FunctionFlags & FUNC_Private)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Private")));
        }
        else
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("Public")));
        }
        if (Entry->MetaData.bCallInEditor)
        {
            Flags.Add(MakeShared<FJsonValueString>(TEXT("CallInEditor")));
        }
        Category = Entry->MetaData.Category.ToString();
        for (const FBPVariableDescription& Local : Entry->LocalVariables)
        {
            Locals.Add(MakeShared<FJsonValueObject>(VariableJson(Local)));
        }
    }
    Signature->SetArrayField(TEXT("flags"), Flags);
    Signature->SetStringField(TEXT("category"), Category);
    Signature->SetArrayField(TEXT("locals"), Locals);
    return Signature;
}

TSharedPtr<FJsonObject> GraphJson(UBlueprint* Blueprint, UEdGraph* Graph, const FString& Kind)
{
    TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();
    Json->SetStringField(TEXT("name"), Graph->GetName());
    Json->SetStringField(TEXT("kind"), Kind);
    if (Kind == TEXT("function"))
    {
        Json->SetObjectField(TEXT("signature"), FunctionSignatureJson(Graph));
    }
    TArray<TSharedPtr<FJsonValue>> Nodes;
    for (UEdGraphNode* Node : Graph->Nodes)
    {
        if (Node != nullptr)
        {
            Nodes.Add(MakeShared<FJsonValueObject>(NodeJson(Blueprint, Node, Kind == TEXT("macro"))));
        }
    }
    Json->SetArrayField(TEXT("nodes"), Nodes);
    return Json;
}
}
